### ISSUE TITLE
Themed Icon for Android 13+

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#174]
Google introduced a new icon technique starting with Android 13 and higher called [Themed Icons](https://developer.android.com/about/versions/13/features#themed-app-icons).
It would be nice if we could support that too. The monochrome icon needs to be designed.
The existing assets may be found in the [media](https://github.com/EvilInsultGenerator/media) repo in the `Icons/Evil Insult Generator/Android` folder.

**Comment by indra057** [comment]
can u please assign me this issue so i can get started with it

**Comment by EvilInsultGenerator** [comment]
> can u please assign me this issue so i can get started with it

Thank you so much for your offer to help. 👍

**Comment by indra057** [comment]
@EvilInsultGenerator sir can u please check my pr and see if anything is wrong and if not can u merge it...also does  it comes under hacktoberfest ?

**Comment by EvilInsultGenerator** [comment]
> @EvilInsultGenerator sir can u please check my pr and see if anything is wrong and if not can u merge it...also does it comes under hacktoberfest ?

I just merged it so it will count for Hacktoberfest. 👌
I noticed that I already uploaded a monochrome icon a year ago. May you send me a screenshot that compares both variants?

**Comment by indra057** [comment]
![Screenshot 2024-10-05 185031](https://github.com/user-attachments/assets/04e62d57-5d72-4fdb-a86a-69a42b8e36ea)

**Comment by indra057** [comment]
@EvilInsultGenerator right side is my icon but it the text is not shown while in themed mode i tried to fix it with most of my knowledge (by using adobe xd ) but issue still persists although the themed icon doesnt looks bad so u can consider!

**Comment by EvilInsultGenerator** [comment]
Let's go with the old monochrome icon then.
Thanks for your input anyway.
